version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neovimconf
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
