# fly.toml app configuration file generated for nvc on 2024-06-09T10:43:12+02:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'nvc'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_SERVER = "true"
  LOG_LEVEL = "info"
  PHX_HOST = 'neovimconf.live'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = 512
  size = 'shared-cpu-1x'
